# Generated by Django 3.2.6 on 2022-11-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=10000)),
                ('lname', models.CharField(max_length=10000)),
                ('ic_number', models.CharField(max_length=10000)),
                ('contact_number', models.CharField(max_length=10000)),
                ('profession', models.CharField(max_length=10000)),
                ('email_id', models.CharField(max_length=10000)),
                ('education', models.CharField(max_length=10000)),
                ('city', models.CharField(max_length=10000)),
            ],
            options={
                'db_table': 'client_registration',
            },
        ),
    ]
