# Generated by Django 3.2.6 on 2022-11-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=10000)),
                ('fname', models.CharField(max_length=10000)),
                ('lname', models.CharField(max_length=10000)),
                ('gender', models.CharField(max_length=100)),
                ('dob', models.DateField(default='')),
                ('education', models.CharField(max_length=10000)),
                ('profession', models.CharField(max_length=10000)),
                ('company_college_name', models.CharField(max_length=10000)),
                ('job_college_location', models.CharField(max_length=10000)),
                ('house_block_no', models.CharField(max_length=10000)),
                ('street_name', models.CharField(max_length=10000)),
                ('town_city', models.CharField(max_length=10000)),
                ('district', models.CharField(max_length=10000)),
                ('state', models.CharField(max_length=10000)),
                ('postal_code', models.CharField(max_length=10000)),
                ('email_id', models.CharField(max_length=10000)),
                ('contact_number', models.CharField(default='', max_length=10000)),
                ('photo_upload', models.ImageField(default='', upload_to='media/photo')),
                ('aadhar_number', models.CharField(max_length=10000)),
                ('aadhar_upload', models.ImageField(default='', upload_to='media/id proof/aadhar')),
                ('drivinglicense_number', models.CharField(default='', max_length=10000)),
                ('drivinglicense_upload', models.ImageField(default='', upload_to='media/id proof/driving license')),
                ('voter_id', models.CharField(default='', max_length=10000)),
                ('voterid_upload', models.ImageField(default='', upload_to='media/id proof/voterid')),
                ('passport_number', models.CharField(default='', max_length=10000)),
                ('passport_upload', models.ImageField(default='', upload_to='media/idproof/passport')),
                ('pan_number', models.CharField(default='', max_length=10000)),
                ('pancard_upload', models.ImageField(default='', upload_to='media/idproof/pancard/')),
                ('rationcard_number', models.CharField(default='', max_length=10000)),
                ('rationcard_upload', models.ImageField(default='', upload_to='media/idproof/rationcard')),
                ('client_uniqueid', models.CharField(max_length=10000)),
                ('created_date', models.DateField(default='')),
                ('seq_id', models.DateField(max_length=10000)),
            ],
            options={
                'db_table': 'client_registration',
            },
        ),
    ]
