# Generated by Django 3.2.13 on 2023-03-14 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client_data',
            old_name='client_id',
            new_name='member_id',
        ),
    ]
