# Generated by Django 3.2.13 on 2023-03-31 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seminar_data',
            old_name='clientid',
            new_name='memberid',
        ),
    ]
