# Generated by Django 3.2.13 on 2023-04-28 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar_data',
            name='seminardate',
            field=models.DateField(default=''),
        ),
    ]
