# Generated by Django 3.2.6 on 2022-11-23 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='seminar_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regid', models.CharField(max_length=10000)),
                ('clientid', models.CharField(max_length=10000)),
                ('payirchiid', models.CharField(max_length=100)),
                ('payirchiname', models.CharField(max_length=10000)),
                ('first_payment', models.CharField(max_length=10000)),
                ('second_payment', models.CharField(max_length=10000)),
                ('third_payment', models.CharField(max_length=10000)),
                ('fourth_payment', models.CharField(max_length=10000)),
                ('first_payment_date', models.DateField(default='')),
                ('second_payment_date', models.DateField(default='')),
                ('third_payment_date', models.DateField(default='')),
                ('fourth_payment_date', models.DateField(default='')),
                ('total', models.CharField(max_length=10000)),
                ('balance', models.CharField(max_length=10000)),
                ('payment_status', models.CharField(max_length=10000)),
                ('introducer', models.CharField(max_length=10000)),
                ('team_leader', models.CharField(max_length=10000)),
                ('assistant_leader', models.CharField(max_length=10000)),
                ('leader', models.CharField(max_length=10000)),
                ('created_date', models.DateField(default='')),
            ],
            options={
                'db_table': 'seminar_registration',
            },
        ),
        migrations.RemoveField(
            model_name='client_data',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='client_data',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='client_data',
            name='seq_id',
        ),
    ]
