# Generated by Django 3.2.13 on 2022-12-24 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20221224_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client_data',
            old_name='member_uniqueid',
            new_name='client_uniqueid',
        ),
        migrations.RenameField(
            model_name='seminar_data',
            old_name='memberid',
            new_name='clientid',
        ),
    ]
