# Generated by Django 3.2.13 on 2023-04-14 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_clientid_seminar_data_memberid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seminar_data',
            old_name='memberid',
            new_name='member_id',
        ),
    ]
