# Generated by Django 3.2.13 on 2023-01-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20221224_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_data',
            name='idproof_upload_path',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='client_data',
            name='photo_upload_path',
            field=models.ImageField(upload_to=''),
        ),
    ]
