# Generated by Django 3.2.13 on 2023-04-17 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_memberid_seminar_data_member_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seminar_data',
            old_name='payirchiid',
            new_name='seminarid',
        ),
        migrations.RenameField(
            model_name='seminar_data',
            old_name='payirchiname',
            new_name='seminarname',
        ),
    ]
