# Generated by Django 3.2.13 on 2023-04-18 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20230417_1104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seminar_data',
            old_name='first_payment',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='seminar_data',
            old_name='fourth_payment',
            new_name='seminardate',
        ),
        migrations.RenameField(
            model_name='seminar_data',
            old_name='second_payment',
            new_name='seminarfee',
        ),
        migrations.RenameField(
            model_name='seminar_data',
            old_name='third_payment',
            new_name='seminarlocation',
        ),
        migrations.RemoveField(
            model_name='seminar_data',
            name='first_payment_date',
        ),
        migrations.RemoveField(
            model_name='seminar_data',
            name='fourth_payment_date',
        ),
        migrations.RemoveField(
            model_name='seminar_data',
            name='second_payment_date',
        ),
        migrations.RemoveField(
            model_name='seminar_data',
            name='third_payment_date',
        ),
    ]
