# Generated by Django 3.2.13 on 2023-05-13 09:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_seminar_data_seminardate'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(max_length=10000)),
                ('seminarid', models.CharField(max_length=10000)),
                ('first_payment_date', models.DateField(blank=True, null=True)),
                ('first_payment', models.CharField(max_length=10000)),
                ('total', models.CharField(max_length=10000)),
                ('balance', models.CharField(max_length=10000)),
                ('payment_status', models.CharField(max_length=10000)),
                ('payments_no', models.CharField(max_length=10000)),
                ('logged_userid', models.CharField(max_length=10000)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'payment_data',
            },
        ),
    ]
