# Generated by Django 3.2.13 on 2023-06-20 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_payment_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seminar_data',
            name='total',
        ),
    ]
