# Generated by Django 3.2.13 on 2023-06-20 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_seminar_data_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment_detail',
            name='total',
        ),
    ]
