# Generated by Django 3.2.13 on 2023-06-28 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_payment_detail_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment_detail',
            old_name='first_payment',
            new_name='payment',
        ),
        migrations.RenameField(
            model_name='payment_detail',
            old_name='first_payment_date',
            new_name='payment_date',
        ),
        migrations.RenameField(
            model_name='seminar_data',
            old_name='first_payment',
            new_name='payment',
        ),
        migrations.RenameField(
            model_name='seminar_data',
            old_name='first_payment_date',
            new_name='payment_date',
        ),
    ]
